### ISSUE TITLE
Enqueue and localize inline scripts

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/WDS-Mega-Menu#3]
See [includes/nav-menu-edit-walker.php:22](https://github.com/WebDevStudios/WDS-Mega-Menu/blob/master/includes/nav-menu-edit-walker.php#L122)

This has caused slowness when large menu's are built. We should try and make this a re-useable function that is enqueued and called with parameters.

**Comment by jazzsequence** [comment]
That link doesn't exist. Possibly because this version of the plugin is an older version of what we're using on projects?

**Comment by aubreypwd** [comment]
It's because we renamed the files. Check out [class-wds-mega-menus-walker-nav-menu-edit.php#L135](https://github.com/WebDevStudios/WDS-Mega-Menu/blob/develop/includes/class-wds-mega-menus-walker-nav-menu-edit.php#L135)

Those inline scripts (there are many) need to be re-done.

**Comment by phatsk** [comment]
Now see https://github.com/WebDevStudios/WDS-Mega-Menu/blob/develop/includes/class-walker-nav-menu-edit.php#L155

**Comment by phatsk** [comment]
This is addressed in #20
