### ISSUE TITLE
The CSS here causes lots of problems

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/WDS-Mega-Menu#5]
[admin.css:899](https://github.com/WebDevStudios/WDS-Mega-Menu/blob/develop/assets/css/admin.css#L899)

This line, specifically, causes the screen options dropdown to break. I'm not sure we need this CSS. It's here because it styles the dropdown for the icon stuff. Maybe we can get some better CSS in place?

**Comment by jazzsequence** [comment]
that line can be removed, i think. it's just core bootstrap css

**Comment by jazzsequence** [comment]
this is fixed. `.hidden` class removed.
