### ISSUE TITLE
Use default icon set if it exists

### ISSUE THREAD

**Issue by jazzsequence** [WebDevStudios/WDS-Mega-Menu#6]
In the branch I was using, I had started to add a fallback to use a default iconset if the theme in use did not have one. That way the plugin can be used out of the box. Need to bring this back and use bundled icons (already in the repo in `/assets/images`)

**Comment by jazzsequence** [comment]
[icons.zip](https://github.com/WebDevStudios/WDS-Mega-Menu/files/503241/icons.zip)
Default icon set and svg-defs.svg file.
We should make sure to add a grunt task for adding new icons similar to what's already in wd_s (copy pasta probably)

**Comment by PavelK27** [comment]
Seems resolved.
